version: "3"
services:
  gitlab:
    build: .
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8081'
        gitlab_shell['custom_hooks_dir'] = '/opt/git-hooks'
    volumes:
    - ./gitlab/config:/etc/gitlab
    - ./gitlab/logs:/var/log/gitlab
    - ./gitlab/data:/var/opt/gitlab
    ports:
    - "8081:8081"
  git:
    build:
      context: .
      dockerfile: Dockerfile.git
    links:
    - gitlab
